spring:

  application:
    name: ${APPLICATION:client}

  config:
    import:
      - optional:classpath:application-common.yaml

app:
  service:
    license:
      server: ${LICENSE_SERVER:}
  license-server: ${LICENSE_SERVER:}
  license-app-id: ${LICENSE_APP_ID:}
  license-code: ${LICENSE_CODE:}
  license-api-security: ${LICENSE_API_SECURITY:true}
