spring:

  application:
    name: ${APPLICATION:client}

  config:
    import:
      - optional:classpath:application-common.yaml

app:
  slogan: ${APP_SLOGAN:!!!}
  license-server: ${LICENSE_SERVER:}
  license-app-id: ${LICENSE_APP_ID:}
  license-code: ${LICENSE_CODE:}
