spring:

  application:
    name: ${APPLICATION:license-server}

  config:
    import:
      - optional:classpath:application-common-local.yaml
      - optional:classpath:application-mysql-local.yaml
      - optional:classpath:application-redis-local.yaml
      - optional:classpath:application-mail-local.yaml

  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:123456}
      roles: ${ADMIN_ROLES:ADMIN}

logging:
  level:
    org.springframework.security: trace

app:
  slogan: ${APP_SLOGAN:!!!}
  api-security: ${API_SECURITY:false}
