spring:

  application:
    name: ${APPLICATION:license-server}

  config:
    import:
      - optional:classpath:application-common.yaml
      - optional:classpath:application-mysql.yaml
      - optional:classpath:application-redis.yaml
      - optional:classpath:application-mail.yaml

  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:}
      roles: ${ADMIN_ROLES:ADMIN}

app:
  admin-token-duration: ${ADMIN_TOKEN_DURATION:PT1H}
  admin-app-id: ${ADMIN_APP_ID:00000000000000000000000000000000}
  admin-license: ${ADMIN_LICENSE:00000000000000000000000000000000}
  license-expires-warning-days: ${LICENSE_EXPIRES_WARNING_DAYS:7,3,1}
  license-expires-warning-email: ${LICENSE_EXPIRES_WARNING_EMAIL:true}
  api-security-enabled: ${API_SECURITY_ENABLED:true}
