spring:

  application:
    name: ${APPLICATION:license-server}

  config:
    import:
      - optional:classpath:application-common-local.yaml
      - optional:classpath:application-mysql-local.yaml
      - optional:classpath:application-redis-local.yaml
      - optional:classpath:application-mail-local.yaml

logging:
  level:
    org.springframework.security: trace

app:
  slogan: ${APP_SLOGAN:!!!}
