version: '1.0'
name: admin
displayName: admin
triggers:
  trigger: auto
  push:
    tags:
      prefix:
        - t-
    paths:
      include:
        - ^admin/.*$
variables:
  NAMESPACE: license
  APPLICATION: admin
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 20.10.0
        commands:
          - cd ${APPLICATION}
          - npm config set registry https://registry.npmmirror.com
          - npm install -g pnpm
          - pnpm config set registry https://registry.npmmirror.com
          - pnpm install -frozen-lockfile
          - pnpm run build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ${APPLICATION}/dist
        caches:
          - ~/.npm
          - ~/.yarn
          - ~/.pnpm
        notify: []
        strategy:
          retry: '0'
  - name: build
    displayName: 构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: aliyun-cr-daodao-bot
        tag: daodao-bot/${NAMESPACE}-${APPLICATION}:${GITEE_BRANCH}
        dockerfile: ${APPLICATION}/Dockerfile
        context: ${APPLICATION}
        artifacts:
          - ${BUILD_ARTIFACT}
        isCache: false
        parameter: {}
        notify: []
        strategy:
          retry: '0'
